In [1]:
!pip install anonymizedf
import pandas as pd
from anonymizedf.anonymizedf import anonymize

Requirement already satisfied: anonymizedf in c:\users\windows\anaconda3\lib\site-packages (1.0.1)
Requirement already satisfied: faker in c:\users\windows\anaconda3\lib\site-packages (from anonymizedf) (14.2.0)
Requirement already satisfied: pandas in c:\users\windows\anaconda3\lib\site-packages (from anonymizedf) (1.4.2)
Requirement already satisfied: python-dateutil>=2.4 in c:\users\windows\anaconda3\lib\site-packages (from faker->anonymizedf) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\windows\anaconda3\lib\site-packages (from python-dateutil>=2.4->faker->anonymizedf) (1.16.0)
Requirement already satisfied: numpy>=1.18.5 in c:\users\windows\anaconda3\lib\site-packages (from pandas->anonymizedf) (1.21.5)
Requirement already satisfied: pytz>=2020.1 in c:\users\windows\anaconda3\lib\site-packages (from pandas->anonymizedf) (2021.3)

# Paso 1: Lectura de datos

In [3]:
df= pd.read_csv('Datos_Microdesafio_Semana7_DE.csv',sep=';')
df.head(12)

,Pais,Comisionado,Reduccion_CO2,Incrmento_P,Inversion_arboles,Fecha,Telefono
0,Argentina,Carlos Veroes,Si,Si,Si,08/07/2022,23467698
1,Colombia,Sofia Andrade,No,No,Si,12/06/2022,76587899
2,Chile,Cristina Valdivia,Si,Si,Si,15/07/2022,76593749
3,Bolivia,Pedro Carlos,No,No,No,01/09/2022,65746474
4,Paraguay,Juan Paraguas,No,Si,Si,04/06/2022,83447474
5,Venezuela,Andres Calamaro,Si,Si,No,03/05/2022,76847383
6,Uruguay,Fernando Tatial,No,No,Si,04/04/2022,13434453
7,Brasil,Gabriel Toeras,Si,Si,No,12/06/2022,37374344
8,Ecuador,Juan Vera,No,No,No,14/05/2022,47477654
9,Peru,Andres Porto,No,No,No,13/05/2022,57737373
10,EEUU,Jennifer Laurence,Si,Si,Si,01/04/2022,84574737
11,Canada,John white,No,Si,Si,04/01/2022,83873734

# Paso 2: Anonimizacion de columnas

In [4]:
# Preparar el dataframe
an = anonymize(df)

In [5]:
fake_df = (
    an
    .fake_names("Comisionado", chaining=True)
    .fake_dates("Fecha", chaining=True)
    .fake_whole_numbers("Telefono", chaining=True)
    .show_data_frame()
)
fake_df

,Pais,Comisionado,Reduccion_CO2,Incrmento_P,Inversion_arboles,Fecha,Telefono,Fake_Comisionado,Fake_Fecha,Fake_Telefono
0,Argentina,Carlos Veroes,Si,Si,Si,08/07/2022,23467698,Arthur Bell,1998-03-27,32012744
1,Colombia,Sofia Andrade,No,No,Si,12/06/2022,76587899,Elliot Cooper,1995-09-14,57199927
2,Chile,Cristina Valdivia,Si,Si,Si,15/07/2022,76593749,Glenn Hughes,2014-10-01,52677089
3,Bolivia,Pedro Carlos,No,No,No,01/09/2022,65746474,Anna Allen,1989-12-25,40725580
4,Paraguay,Juan Paraguas,No,Si,Si,04/06/2022,83447474,Dr Roger Lucas,2008-04-30,47848678
5,Venezuela,Andres Calamaro,Si,Si,No,03/05/2022,76847383,Amanda Townsend-Chapman,1976-02-21,73675378
6,Uruguay,Fernando Tatial,No,No,Si,04/04/2022,13434453,Lucy Walker,1997-04-13,46789885
7,Brasil,Gabriel Toeras,Si,Si,No,12/06/2022,37374344,Lee May,1995-09-14,48545368
8,Ecuador,Juan Vera,No,No,No,14/05/2022,47477654,Gerard Palmer,2000-04-21,17588723
9,Peru,Andres Porto,No,No,No,13/05/2022,57737373,Michael Stephenson,1978-02-13,44730315
10,EEUU,Jennifer Laurence,Si,Si,Si,01/04/2022,84574737,Tom Hope,2010-05-08,15261100
11,Canada,John white,No,Si,Si,04/01/2022,83873734,Lucy Moore-Jones,1992-08-28,58611587
12,Mexico,Andres Fernandez,Si,Si,No,08/05/2022,64634746,Dr Denise Wood,1977-09-07,74666944
13,Costa Rica,Pedro Urrutia,No,No,Si,09/06/2022,14544643,Beverley Griffiths,2008-06-08,19945767
14,Jamaica,Michael Sophit,No,No,No,26/07/2022,75638664,Bernard McDonald-Roberts,1981-10-17,37718203

In [8]:
fake_df.columns

Index(['Pais ', 'Comisionado', 'Reduccion_CO2', 'Incrmento_P',
       'Inversion_arboles', 'Fecha', 'Telefono', 'Fake_Comisionado',
       'Fake_Fecha', 'Fake_Telefono'],
      dtype='object')

# Paso 3: Eleccion de columnas para alimentar database

In [13]:
df_final=fake_df[['Pais ','Fake_Comisionado','Reduccion_CO2','Incrmento_P','Inversion_arboles',
                  'Fake_Fecha','Fake_Telefono']]
df_final.columns=[['Pais ', 'Comisionado', 'Reduccion_CO2', 'Incrmento_P',
                   'Inversion_arboles', 'Fecha', 'Telefono',]]
df_final

,Pais,Comisionado,Reduccion_CO2,Incrmento_P,Inversion_arboles,Fecha,Telefono
0,Argentina,Arthur Bell,Si,Si,Si,1998-03-27,32012744
1,Colombia,Elliot Cooper,No,No,Si,1995-09-14,57199927
2,Chile,Glenn Hughes,Si,Si,Si,2014-10-01,52677089
3,Bolivia,Anna Allen,No,No,No,1989-12-25,40725580
4,Paraguay,Dr Roger Lucas,No,Si,Si,2008-04-30,47848678
5,Venezuela,Amanda Townsend-Chapman,Si,Si,No,1976-02-21,73675378
6,Uruguay,Lucy Walker,No,No,Si,1997-04-13,46789885
7,Brasil,Lee May,Si,Si,No,1995-09-14,48545368
8,Ecuador,Gerard Palmer,No,No,No,2000-04-21,17588723
9,Peru,Michael Stephenson,No,No,No,1978-02-13,44730315
10,EEUU,Tom Hope,Si,Si,Si,2010-05-08,15261100
11,Canada,Lucy Moore-Jones,No,Si,Si,1992-08-28,58611587
12,Mexico,Dr Denise Wood,Si,Si,No,1977-09-07,74666944
13,Costa Rica,Beverley Griffiths,No,No,Si,2008-06-08,19945767
14,Jamaica,Bernard McDonald-Roberts,No,No,No,1981-10-17,37718203

# Paso 4: Conexion a Redshift

In [ ]:
from sqlalchemy import create_engine, text
import psycopg2
# Caso PostgreSQL local
engine= create_engine("postgresql://postgres:XXXXX@localhost:5432/BDE_POLITICAS_FIN")
# Caso redshift
#engine= conn = create_engine('postgresql://username:password@yoururl.com:5439/yourdatabase')

# Paso 5: Enviar tabla a la base de datos

In [ ]:
df = df_final.to_sql('POLITICAS_2050', engine, if_exists='replace', index=False)