In [1]:
import urllib.request
url = 'https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/cars_clus.csv'
filename = 'cars_clus.csv'
df=urllib.request.urlretrieve(url, filename)
import pandas as pd
pdf = pd.read_csv(filename,na_values = "$null$")
pdf

,manufact,model,sales,resale,type,price,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg,lnsales,partition
0,Acura,Integra,16.919,16.360,0.0,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2.828,0.0
1,Acura,TL,39.384,19.875,0.0,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,3.673,0.0
2,Acura,CL,14.114,18.225,0.0,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,2.647,0.0
3,Acura,RL,8.588,29.725,0.0,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,2.150,0.0
4,Audi,A4,20.397,22.255,0.0,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,3.015,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,Volvo,V70,17.531,NaN,0.0,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,2.864,0.0
155,Volvo,C70,3.493,NaN,0.0,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,1.251,0.0
156,Volvo,S80,18.969,NaN,0.0,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,2.943,0.0
157,NaN,newCar,NaN,NaN,NaN,21.50,1.5,76.0,106.3,67.9,175.0,2.932,11.9,46.0,NaN,1.0
158,NaN,newTruck,NaN,NaN,NaN,34.20,3.5,167.0,109.8,75.2,188.4,4.508,17.2,26.0,NaN,1.0

# Parte 1

In [10]:
pdf=pdf.dropna()
pdf

,manufact,model,sales,resale,type,price,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg,lnsales,partition
0,Acura,Integra,16.919,16.360,0.0,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2.828,0.0
1,Acura,TL,39.384,19.875,0.0,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,3.673,0.0
3,Acura,RL,8.588,29.725,0.0,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,2.150,0.0
4,Audi,A4,20.397,22.255,0.0,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,3.015,0.0
5,Audi,A6,18.780,23.555,0.0,33.95,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,2.933,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,Volkswagen,Golf,9.761,11.425,0.0,14.90,2.0,115.0,98.9,68.3,163.3,2.767,14.5,26.0,2.278,0.0
146,Volkswagen,Jetta,83.721,13.240,0.0,16.70,2.0,115.0,98.9,68.3,172.3,2.853,14.5,26.0,4.427,0.0
147,Volkswagen,Passat,51.102,16.725,0.0,21.20,1.8,150.0,106.4,68.5,184.1,3.043,16.4,27.0,3.934,0.0
148,Volkswagen,Cabrio,9.569,16.575,0.0,19.99,2.0,115.0,97.4,66.7,160.4,3.079,13.7,26.0,2.259,0.0
149,Volkswagen,GTI,5.596,13.760,0.0,17.50,2.0,115.0,98.9,68.3,163.3,2.762,14.6,26.0,1.722,0.0

In [9]:
pdf

,manufact,model,sales,resale,type,price,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg,lnsales,partition
0,Acura,Integra,16.919,16.360,0.0,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2.828,0.0
1,Acura,TL,39.384,19.875,0.0,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,3.673,0.0
2,Acura,CL,14.114,18.225,0.0,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,2.647,0.0
3,Acura,RL,8.588,29.725,0.0,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,2.150,0.0
4,Audi,A4,20.397,22.255,0.0,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,3.015,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,Volvo,V70,17.531,NaN,0.0,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,2.864,0.0
155,Volvo,C70,3.493,NaN,0.0,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,1.251,0.0
156,Volvo,S80,18.969,NaN,0.0,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,2.943,0.0
157,NaN,newCar,NaN,NaN,NaN,21.50,1.5,76.0,106.3,67.9,175.0,2.932,11.9,46.0,NaN,1.0
158,NaN,newTruck,NaN,NaN,NaN,34.20,3.5,167.0,109.8,75.2,188.4,4.508,17.2,26.0,NaN,1.0

# Parte 2

In [11]:
pdf[['manufact','price']].groupby(by='manufact').mean()

                   price
manufact
Acura          30.633333
Audi           39.980000
BMW            36.150000
Buick          26.781250
Cadillac       36.856667
Chevrolet      20.164375
Chrysler       22.280000
Dodge          24.170556
Ford           21.920500
Honda          20.277000
Hyundai        12.165667
Infiniti       29.465000
Jeep           20.991667
Lexus          41.105000
Lincoln        41.205000
Mercedes-Benz  58.487500
Mercury        20.748333
Mitsubishi     22.167429
Nissan         23.167200
Oldsmobile     27.829250
Plymouth       15.856667
Pontiac        22.412000
Porsche        62.473333
Saturn         12.503333
Toyota         21.934750
Volkswagen     18.058000

# Parte 3

In [16]:
pdf=pdf.assign(Valor_nuevo= lambda x: x['price']*1.05)
pdf

,manufact,model,sales,resale,type,price,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg,lnsales,partition,Valor_nuevo
0,Acura,Integra,16.919,16.360,0.0,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2.828,0.0,22.5750
1,Acura,TL,39.384,19.875,0.0,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,3.673,0.0,29.8200
3,Acura,RL,8.588,29.725,0.0,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,2.150,0.0,44.1000
4,Audi,A4,20.397,22.255,0.0,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,3.015,0.0,25.1895
5,Audi,A6,18.780,23.555,0.0,33.95,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,2.933,0.0,35.6475
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,Volkswagen,Golf,9.761,11.425,0.0,14.90,2.0,115.0,98.9,68.3,163.3,2.767,14.5,26.0,2.278,0.0,15.6450
146,Volkswagen,Jetta,83.721,13.240,0.0,16.70,2.0,115.0,98.9,68.3,172.3,2.853,14.5,26.0,4.427,0.0,17.5350
147,Volkswagen,Passat,51.102,16.725,0.0,21.20,1.8,150.0,106.4,68.5,184.1,3.043,16.4,27.0,3.934,0.0,22.2600
148,Volkswagen,Cabrio,9.569,16.575,0.0,19.99,2.0,115.0,97.4,66.7,160.4,3.079,13.7,26.0,2.259,0.0,20.9895
149,Volkswagen,GTI,5.596,13.760,0.0,17.50,2.0,115.0,98.9,68.3,163.3,2.762,14.6,26.0,1.722,0.0,18.3750

# Parte 4

In [19]:
pdf[['manufact','horsepow','mpg']].groupby(by='manufact').describe()

              horsepow                                                        \
                 count        mean         std    min     25%    50%     75%
manufact
Acura              3.0  191.666667   45.368859  140.0  175.00  210.0  217.50
Audi               3.0  220.000000   81.853528  150.0  175.00  200.0  255.00
BMW                2.0  193.000000    0.000000  193.0  193.00  193.0  193.00
Buick              4.0  206.250000   26.575365  175.0  197.50  205.0  213.75
Cadillac           3.0  250.000000   43.301270  200.0  237.50  275.0  275.00
Chevrolet          8.0  170.000000   84.852814   55.0  118.75  172.5  185.00
Chrysler           5.0  183.200000   45.866109  132.0  163.00  168.0  200.00
Dodge              9.0  195.888889  100.258970  120.0  150.00  168.0  175.00
Ford              10.0  176.400000   43.097306  110.0  151.25  180.0  207.50
Honda              5.0  160.400000   45.445572  106.0  135.00  146.0  205.00
Hyundai            3.0  126.666667   30.287511   92.0  116.00  140.0  144.00
Infiniti           1.0  227.000000         NaN  227.0  227.00  227.0  227.00
Jeep               3.0  168.333333   41.932485  120.0  155.00  190.0  192.50
Lexus              3.0  241.666667   42.524503  210.0  217.50  225.0  257.50
Lincoln            2.0  245.000000   42.426407  215.0  230.00  245.0  260.00
Mercedes-Benz      4.0  245.750000   52.671150  185.0  212.00  248.0  281.75
Mercury            6.0  163.833333   36.361610  125.0  132.00  161.5  192.50
Mitsubishi         7.0  165.142857   33.052628  113.0  149.50  161.0  186.50
Nissan             5.0  168.600000   34.839633  126.0  155.00  170.0  170.00
Oldsmobile         4.0  193.750000   41.508031  150.0  176.25  187.5  205.00
Plymouth           3.0  138.000000   10.392305  132.0  132.00  132.0  141.00
Pontiac            5.0  185.000000   22.638463  150.0  175.00  195.0  200.00
Porsche            3.0  272.333333   47.920072  217.0  258.50  300.0  300.00
Saturn             3.0  108.000000   13.856406  100.0  100.00  100.0  112.00
Toyota             8.0  156.500000   40.609640  120.0  131.50  141.0  165.00
Volkswagen         5.0  122.000000   15.652476  115.0  115.00  115.0  115.00

                       mpg                                                 \
                 max count       mean       std   min    25%   50%    75%
manufact
Acura          225.0   3.0  25.000000  3.000000  22.0  23.50  25.0  26.50
Audi           310.0   3.0  23.333333  3.214550  21.0  21.50  22.0  24.50
BMW            193.0   2.0  24.400000  0.565685  24.0  24.20  24.4  24.60
Buick          240.0   4.0  24.250000  0.957427  23.0  23.75  24.5  25.00
Cadillac       275.0   3.0  22.000000  0.000000  22.0  22.00  22.0  22.00
Chevrolet      345.0   8.0  28.625000  7.327785  22.0  25.00  26.0  28.50
Chrysler       253.0   5.0  24.800000  1.643168  23.0  24.00  24.0  26.00
Dodge          450.0   9.0  20.444444  4.927248  15.0  16.00  19.0  24.00
Ford           240.0  10.0  22.100000  4.012481  16.0  19.50  22.0  24.00
Honda          210.0   5.0  25.000000  4.847680  19.0  23.00  24.0  27.00
Hyundai        148.0   3.0  27.666667  3.055050  25.0  26.00  27.0  29.00
Infiniti       227.0   1.0  25.000000       NaN  25.0  25.00  25.0  25.00
Jeep           195.0   3.0  18.666667  1.527525  17.0  18.00  19.0  19.50
Lexus          290.0   3.0  22.666667  0.577350  22.0  22.50  23.0  23.00
Lincoln        275.0   2.0  21.500000  0.707107  21.0  21.25  21.5  21.75
Mercedes-Benz  302.0   4.0  23.000000  2.943920  20.0  20.75  23.0  25.25
Mercury        210.0   6.0  23.666667  4.589844  18.0  21.00  22.5  27.00
Mitsubishi     210.0   7.0  22.857143  3.933979  18.0  20.50  22.0  24.50
Nissan         222.0   5.0  24.000000  4.242641  19.0  21.00  25.0  25.00
Oldsmobile     250.0   4.0  22.000000  2.449490  19.0  21.25  22.0  22.75
Plymouth       150.0   3.0  26.666667  2.516611  24.0  25.50  27.0  28.00
Pontiac        205.0   5.0  25.200000  1.095445  24.0  25.00  25.0  25.00
Porsche        300.0   3.0  22.000000  1.000000  21.0  21.50  22.0  22.50
Saturn         124.0   3.0  32.333333  1.154701  31.0  32.00  33.0  33.00
Toyota         230.0   8.0  25.625000  5.527529  15.0  23.00  26.5  28.00
Volkswagen     150.0   5.0  26.200000  0.447214  26.0  26.00  26.0  26.00


                max
manufact
Acura          28.0
Audi           27.0
BMW            24.8
Buick          25.0
Cadillac       22.0
Chevrolet      45.0
Chrysler       27.0
Dodge          29.0
Ford           30.0
Honda          32.0
Hyundai        31.0
Infiniti       25.0
Jeep           20.0
Lexus          23.0
Lincoln        22.0
Mercedes-Benz  26.0
Mercury        30.0
Mitsubishi     30.0
Nissan         30.0
Oldsmobile     25.0
Plymouth       29.0
Pontiac        27.0
Porsche        23.0
Saturn         33.0
Toyota         33.0
Volkswagen     27.0